version = 0.1

[default.global.parameters]
stack_name = "mobile-devices"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = [
  "DBHOST=ivocdev.cxiqcy2uo0c3.eu-central-1.rds.amazonaws.com",
  "DBNAME=ivocdev",
  "DBUSER=ivoc",
  "DBPASSWORD=ivocDevDB!",
  "REGION=eu-central-1"
]

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
