AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  device.x

Resources:
  MyExistingHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default

  UpdateStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/update-status/
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Timeout: 30
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource:
                - arn:aws:s3:::ivocdevices/*
      Events:
        UpdateStatus:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyExistingHttpApi
            Path: /device/update-status
            Method: post
    Metadata:
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  UpdateStatusApi:
    Description: "API Gateway endpoint for UpdateStatusFunction"
    Value:
      Fn::Sub: "https://${MyExistingHttpApi}.execute-api.${AWS::Region}.amazonaws.com/device/update-status"
