AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  device.x

Resources:
  MyExistingHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
  UpdateStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/update-status/
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - arm64
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource:
                - arn:aws:s3:::ivocdevices/*
      Events:
        UpdateStatus:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            ApiId: !Ref MyExistingHttpApi
            Path: /device/update-status
            Method: post

