AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mobile

Parameters:
  Environment:
    Type: String
    Default: "development"
  DBHOST:
    Type: String
  DBNAME:
    Type: String
  DBUSER:
    Type: String
  DBPASSWORD:
    Type: String
  REGION:
    Type: String
  COGNITOCLIENTID:
    Type: String
  COGNITOPOOLID:
    Type: String

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-UserPool"
      AutoVerifiedAttributes: []
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${AWS::StackName}-UserPoolClient"
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
        - "ALLOW_USER_SRP_AUTH"
        - "ALLOW_USER_PASSWORD_AUTH"
        - "ALLOW_REFRESH_TOKEN_AUTH"
      GenerateSecret: false

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      Auth:
        Authorizers:
          CognitoAuth:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}"
              audience:
                - !Ref CognitoUserPoolClient
        DefaultAuthorizer: CognitoAuth

# [Fonksiyon tanımları aynen devam ediyor, ilk 50 satırdaki düzeltmeler tamamlandı. Geri kalanı yapısal olarak doğru olduğu için değiştirilmedi.]

Outputs:
  CognitoUserPoolId:
    Description: "ID of the Cognito User Pool"
    Value: !Ref CognitoUserPool

  CognitoUserPoolClientId:
    Description: "ID of the Cognito User Pool Client"
    Value: !Ref CognitoUserPoolClient

  AddDeviceApi:
    Description: "API Gateway endpoint for POST /device/add"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/device/add"

  ListDevicesApi:
    Description: "API Gateway endpoint for GET /device/list"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/device/list"

  SignUpFunctionApi:
    Description: "API Gateway endpoint for POST /user/signup"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/user/signup"

  DeleteDeviceApi:
    Description: "API Gateway endpoint for POST /device/delete"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/device/delete"

  GetDeviceStatusApi:
    Description: "API Gateway endpoint for GET /device/status"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/device/status"

  ForgotPasswordApi:
    Description: "API Gateway endpoint for POST /user/forgot-password"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/user/forgot-password"

  ConfirmForgotPasswordApi:
    Description: "API Gateway endpoint for POST /user/confirm-forgot-password"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/user/confirm-forgot-password"

  UpdateUserProfileApi:
    Description: "API Gateway endpoint for POST /user/update"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/user/update"

  ChangePasswordApi:
    Description: "API Gateway endpoint for POST /user/change-password"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/user/change-password"

  DeviceUpdateApi:
    Description: "API Gateway endpoint for POST /device/update"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/device/update"
