AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  device

  Sample SAM Template for device

Globals:
  Function:
    Timeout: 30

Resources:
  UpdateStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/update_status/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Environment:
        Variables:
          DB_HOST: ""
          DB_NAME: ""
          DB_USER: ""
          DB_PASSWORD: ""
          REGION: ""
          ENV: ""
          BUCKET_NAME: ""
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: post

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  UpdateStatusFunction:
    Description: "Update Status Lambda Function ARN"
    Value: !GetAtt UpdateStatusFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt UpdateStatusFunctionRole.Arn
