AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  device

Resources:
 MyExistingHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default

 UpdateStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/update-status/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Timeout: 30
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource:
                - arn:aws:s3:::ivocdevices/*
      Environment:
        Variables:
          DB_HOST: ""
          DB_NAME: ""
          DB_USER: ""
          DB_PASSWORD: ""
          REGION: ""
          ENV: ""
      Events:
        UpdateStatus:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyExistingHttpApi
            Path: /device/update-status
            Method: post
    Metadata:
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  UpdateStatusApi:
    Description: "API Gateway endpoint for UpdateStatusFunction"
    Value:
      Fn::Sub: "https://${MyExistingHttpApi}.execute-api.${AWS::Region}.amazonaws.com/device/update-status"
