AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: device

Parameters:
  Environment:
    Type: String
    Default: "development"
  DBHOST:
    Type: String
  DBNAME:
    Type: String
  DBUSER:
    Type: String
  DBPASSWORD:
    Type: String
  REGION:
    Type: String

Resources:
  MyExistingHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default

  UpdateStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/update-status/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 30
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - lambda:InvokeFunction
              Resource:
                - arn:aws:s3:::ivocdevices/*
                # AddDeviceFunction'ın **tam ARN**’sini buraya ekliyoruz:
                - !GetAtt AddDeviceFunction.Arn
      Environment:
        Variables:
          DB_HOST:        !Ref DBHOST
          DB_NAME:        !Ref DBNAME
          DB_USER:        !Ref DBUSER
          DB_PASSWORD:    !Ref DBPASSWORD
          REGION:         !Ref REGION
          ENV:            !Ref Environment
          ADD_DEVICE_FUNCTION_NAME: !Ref AddDeviceFunction
      Events:
        UpdateStatus:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyExistingHttpApi
            Path: /device/update-status
            Method: post

  AddDeviceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/add-device/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 30
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - rds-db:connect
              Resource: "*" 
      Environment:
        Variables:
          DB_HOST:     !Ref DBHOST
          DB_NAME:     !Ref DBNAME
          DB_USER:     !Ref DBUSER
          DB_PASSWORD: !Ref DBPASSWORD
          REGION:      !Ref REGION
          ENV:         !Ref Environment
      Events:
        AddDevice:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyExistingHttpApi
            Path: /device/add
            Method: post

Outputs:
  UpdateStatusApi:
    Description: "API Gateway endpoint for UpdateStatusFunction"
    Value: !Sub "https://${MyExistingHttpApi}.execute-api.${AWS::Region}.amazonaws.com/device/update-status"

  AddDeviceApi:
    Description: "API Gateway endpoint for AddDeviceFunction"
    Value: !Sub "https://${MyExistingHttpApi}.execute-api.${AWS::Region}.amazonaws.com/device/add"
