AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  device

Parameters:
  Environment:
    Type: String
    Default: "development"
  DBHOST:
    Type: String
  DBNAME:
    Type: String
  DBUSER:
    Type: String
  DBPASSWORD:
    Type: String
  REGION:
    Type: String

Resources:
 MyExistingHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default

 UpdateStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/update-status/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Timeout: 30
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource:
                - arn:aws:s3:::ivocdevices/*
      Environment:
        Variables:
          DB_HOST: !Ref DBHOST
          DB_NAME: !Ref DBNAME
          DB_USER: !Ref DBUSER
          DB_PASSWORD: !Ref DBPASSWORD
          REGION: !Ref REGION
          ENV: !Ref Environment
      Events:
        UpdateStatus:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyExistingHttpApi
            Path: /device/update-status
            Method: post
    Metadata:
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  UpdateStatusApi:
    Description: "API Gateway endpoint for UpdateStatusFunction"
    Value:
      Fn::Sub: "https://${MyExistingHttpApi}.execute-api.${AWS::Region}.amazonaws.com/device/update-status"
